# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmux" do
  name "pmux"
  desc "Secure remote tmux access from the PocketMux mobile app"
  homepage "https://pmux.io"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmux"

  on_macos do
    url "https://github.com/ShiftinBits/pmux-agent/releases/download/v#{version}/pmux-agent_#{version}_Darwin_universal.zip"
    sha256 "0d9dc5e53153e76cb04a029092a9912bd393eaa093f384646864ff802aa90821"
  end

  on_linux do
    on_intel do
      url "https://github.com/ShiftinBits/pmux-agent/releases/download/v#{version}/pmux-agent_#{version}_Linux_x86_64.tar.gz"
      sha256 "291801aad8a7ca99e5b82bcfec61496cf764e32d78bebfd17d090ae3cb0a6915"
    end
    on_arm do
      url "https://github.com/ShiftinBits/pmux-agent/releases/download/v#{version}/pmux-agent_#{version}_Linux_arm64.tar.gz"
      sha256 "2174c417739e027b3dec5d036b4b2626f1c0230efcc0db6ceae6bb6b6004fb6d"
    end
  end

  # No zap stanza required
end
