# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmux" do
  name "pmux"
  desc "Secure and private remote tmux access from your phone"
  homepage "https://pmux.io"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmux"

  on_macos do
    url "https://github.com/ShiftinBits/pmux-agent/releases/download/v#{version}/pmux-agent_#{version}_Darwin_universal.zip"
    sha256 "0d87a5dc6dc86aafd3966fe8936a04ea471e5a03949e61a6ccf72b7aa4e69a37"
  end

  on_linux do
    on_intel do
      url "https://github.com/ShiftinBits/pmux-agent/releases/download/v#{version}/pmux-agent_#{version}_Linux_x86_64.tar.gz"
      sha256 "236fe649cb43d8a9f221eefccab5fcf37bedc6343eb73ff5e5e6943b37c5d2f1"
    end
    on_arm do
      url "https://github.com/ShiftinBits/pmux-agent/releases/download/v#{version}/pmux-agent_#{version}_Linux_arm64.tar.gz"
      sha256 "daa19392852ec6a335ce1360cbf3978dfec21675ac469ef6e209a8eebd4e19bc"
    end
  end

  uninstall_preflight do
    system_command "#{staged_path}/pmux", args: ["uninstall", "--keep-config", "--yes"]
  end

  caveats do
    "The pmux agent service will be stopped and removed on uninstall."
    ""
    "For full cleanup (including un-registering this host from the"
    "signaling server), run before uninstalling:"
    ""
    "  pmux uninstall"
  end

  uninstall launchctl: [
      "io.pmux.agent",
    ],
    delete: [
      "~/Library/LaunchAgents/io.pmux.agent.plist",
    ]

  zap trash: [
      "~/.config/pmux",
    ]

end
